services:
  
  backend:
    build: ./backend
    container_name: nutrical-backend
    ports:
      - "3000:3000"
      - "5555:5555"
    env_file:
      - ./backend/.env
    environment:
      ##- DB_HOST=db
      ##- DB_PORT=5432
      ##- DB_NAME=nutrical
      ##- DB_USER=nutrical_user
      ##- DB_PASSWORD=nutrical_password
      ## esos atributos ya no se usan, prisma los manejará a través de DATABASE_URL
      - DATABASE_URL=postgresql://nutrical_user:nutrical_password@db:5432/nutrical?schema=public
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules

  db:
    image: postgres:15-alpine
    container_name: nutrical-db
    environment:
      POSTGRES_USER: nutrical_user
      POSTGRES_PASSWORD: nutrical_password
      POSTGRES_DB: nutrical
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nutrical_user -d nutrical"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: