
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// import "dotenv/config"; esto genera muchos problemas
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: `${process.cwd()}/prisma/schema.prisma`,
  migrations: {
    path: `${process.cwd()}/prisma/migrations`,
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});

